// keto diet
// miake technique of the day box up top, and just rotate it
// tipcrypto - leave a tip in cryto
// make it so the techniqeue dev can just write to an api to save crud to user, I provide that
// just hike into jacks peadk or Santa with everything
// being you would be different than playing you in a play, that's what being a carecture of oneself is...
// Grab a technique, add it to your techniques stack, do your life better, that's all

export const state = () => ({
  techniquesdata: [
    {
      name: 'OKRs',
      blurb: 'Objectives and Key Results goal-setting framework',
      votes: 0,
      description: '',
      id: '1f9500d2-fd27-422e-acc6-48198d0de5c2',
      author: '',
      from: 'book',
      comments: [{}, {}, {}],
      category: 'business',
      img: '',
    },
    {
      name: 'Habit Stacking',
      blurb: 'Pair new habits with existing habits',
      votes: 0,
      description: '',
      id: '1f9500d2-fd27-422e-acc6-48198d0de5c2',
      author: '',
      from: 'podcast',
      comments: [{}, {}, {}],
      category: 'personal',
      img: '',
    },
    {
      name: 'Self Distancing',
      blurb: 'View your experience as an observer',
      votes: 0,
      description: '',
      id: '1f9500d2-fd27-422e-acc6-48198d0de5c2',
      author: '',
      from: 'video',
      comments: [{}, {}, {}],
      category: 'personal',
      img: '',
    },
    {
      name: '30 Day Challenges',
      blurb: 'Do one thing every day for 30 days',
      votes: 0,
      description: '',
      id: '1f9500d2-fd27-422e-acc6-48198d0de5c2',
      author: '',
      from: ['book', 'podcast', 'video', 'unknown'],
      comments: [{}, {}, {}],
      category: 'personal',
      img: '',
    },
    {
      name: '5 Year Plan',
      blurb: 'Write your 5 year plan and get clear',
      votes: 0,
      description: '',
      id: '1f9500d2-fd27-422e-acc6-48198d0de5c2',
      author: '',
      from: ['book', 'podcast', 'video', 'unknown'],
      comments: [{}, {}, {}],
      category: 'personal',
      img: '',
    },
    {
      name: 'Shutdown Ritual',
      blurb: 'Actually shut off work mentally for the day',
      votes: 0,
      description: '',
      id: '1f9500d2-fd27-422e-acc6-48198d0de5c2',
      author: '',
      from: ['book', 'podcast', 'video', 'unknown'],
      comments: [{}, {}, {}],
      category: 'personal',
      img: '',
    },
    {
      name: 'User Story',
      blurb: 'As a ___ I want ___ so that ___',
      votes: 0,
      description: '',
      id: '1f9500d2-fd27-422e-acc6-48198d0de5c2',
      author: '',
      from: ['book', 'podcast', 'video', 'unknown'],
      comments: [{}, {}, {}],
      category: 'business',
      img: '',
    },
    {
      name: 'Being, Doing, Becoming',
      blurb: '...',
      votes: 0,
      description: '',
      id: '1f9500d2-fd27-422e-acc6-48198d0de5c2',
      author: '',
      from: ['book', 'podcast', 'video', 'unknown'],
      comments: [{}, {}, {}],
      category: 'personal',
      img: '',
    },
    {
      name: 'Self Congruence',
      // https://www.youtube.com/watch?v=E8cSGX02bqA&t=3681
      // around the hour mark
      blurb: '...',
      votes: 0,
      description: '',
      id: '1f9500d2-fd27-422e-acc6-48198d0de5c2',
      author: '',
      from: ['book', 'podcast', 'video', 'unknown'],
      comments: [{}, {}, {}],
      category: 'personal',
      img: '',
    },
  ],
  sidebarData: [
    {
      name: "Do and Don't lists",
      blurb: "Make To Don'ts explict",
      id: '1f9500d2-fd27-422e-acc6-48198d0fsdfsd',
      img: '',
    },
    {
      name: 'Alternate Life Visioning',
      blurb: 'Design alternate futures',
      id: '1f9500d2-fd27-422e-acc6-48198d02343gf',
      img: '',
    },
    {
      name: 'Live the Shadow',
      blurb: 'Explore your shadow',
      id: '1f9500d2-fd27-422e-acc6-48198d0dkloj4',
      img: '',
    },
  ],
})
